dataset:
  type: folder # in folder, csv, pickle
  dataset_path: ../Dataset/fakenewsdata1/Public Data
  dataset_name: Buzzfeed Political News Dataset

paths:
  GloVe_adress: ../glove6B/glove.6B.100d.txt
  encoder_path: transformer/model/encoder_bpe_40000.json
  bpe_path: transformer/model/vocab_40000.bpe

embedding:
  method_decomposition_embedding: decomposition
  #LDA - GloVe - Transformer -
  method_embedding_glove: mean
  rank_parafac_decomposition: 10
  size_word_co_occurrence_window: 5
  use_frequency: No
  vocab_size: -1
  vocab_util_pourcentage: 1

graph:
  num_nearest_neighbours: 5
  method_create_graph: GloVe

stats:
  num_fake_articles: 100
  num_real_articles: 100
  num_unknown_labels: 160
  proportion_true_fake_label: 0.5
  iteration_stat: 20

learning:
  method_learning: FaBP
  cuda: No
  hidden: 16
  dropout: 0.5
  lr: 0.01
  weight_decay: 5e-4
  fastmode: No
  epochs: 1000
  layers: 2
